name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * *'

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v9
        with:
          source-url: https://github.com/jchw-forks/magic-nix-cache/releases/download/nightly/magic-nix-cache-X64-Linux
      - uses: DeterminateSystems/flake-checker-action@v9
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Run nix flake checks
        run: nix flake check
